export type Lang = "en" | "it" | "sq" | "de" | "fr" | "ar";

export type Copy = (typeof COPY)[Lang];

export const COPY = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      contact: "Contact",
      cta: "Book a consultation",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Albania",
      title: ["CRM, automation, and AI", "engineered for growth."] as [string, string],
      lede: "We help ambitious companies turn the Salesforce ecosystem, iPaaS automation, and full-stack engineering into measurable revenue.",
      ctaPrimary: "Book a free consultation",
      ctaSecondary: "Explore our services",
      stats: [
        { v: "20+", l: "Closed projects" },
        { v: "100+", l: "Salesforce certifications" },
        { v: "1", l: "Office · Tirana" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Certified across the platform.",
      lede: "From Sales Cloud to Agentforce and Data Cloud: our consultants hold active certifications and ship production work every quarter. Velior is a registered Salesforce Consulting Partner.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "What we do",
      title: "Four pillars. One stack, shipped end-to-end.",
      items: [
        {
          n: "01",
          t: "Salesforce",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau and Agentforce: implemented, integrated, and tuned for ROI.",
          bullets: ["Implementation & migration", "Lightning & Apex development", "Reporting & dashboards", "Agentforce & AI agents"],
        },
        {
          n: "02",
          t: "Full-stack engineering",
          d: "Custom software in Next.js, Node, Python and Go: built with the same rigour as the platforms we integrate.",
          bullets: ["Next.js / Angular / Vue apps", "FastAPI & Node services", "Postgres, Mongo, Redis", "DevOps & observability"],
        },
        {
          n: "03",
          t: "AI & agents",
          d: "LLM, RAG and agent systems engineered for production: grounded in your data, governed, and measurable.",
          bullets: ["LLM & RAG pipelines", "Embeddings & vector search", "Agentforce & custom agents", "Evaluation & guardrails"],
        },
        {
          n: "04",
          t: "Process automation",
          d: "End-to-end iPaaS workflows on n8n and Make. We retire manual work, eliminate copy-paste errors, and connect every system you already pay for.",
          bullets: ["n8n & Make workflows", "API & webhook orchestration", "Document & data pipelines", "Operational monitoring"],
        },
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "From discovery to production, in clear steps.",
      steps: [
        { n: "01", t: "Discovery", d: "We audit your stack, data, and processes to identify bottlenecks and opportunities. You receive a written diagnosis and a prioritised roadmap." },
        { n: "02", t: "Design", d: "We define solution architecture, data model, integrations, and acceptance criteria. Nothing gets built before scope and outcomes are signed off." },
        { n: "03", t: "Implement", d: "Iterative delivery with regular demos and transparent progress. Clean code, reviewed and documented as we go: no black boxes." },
        { n: "04", t: "Support", d: "Hand-off with training, runbooks, and a dedicated SLA. We stay close to evolve the platform as your business grows." },
      ],
    },
    cases: {
      eyebrow: "Selected work",
      title: "Outcomes, not screenshots.",
      lede: "A few recent engagements. Real names available under NDA: get in touch for the full deck.",
      items: [
        { tag: "Manufacturing · Sales Cloud", t: "Unified pipeline across 11 EU countries", m: [{ v: "−42%", l: "Reporting time" }, { v: "3.1×", l: "Lead qualification speed" }, { v: "€1.8M", l: "Recovered pipeline visibility" }] },
        { tag: "Insurance · Agentforce + Data Cloud", t: "Customer-service AI agent on legacy stack", m: [{ v: "68%", l: "Tickets auto-resolved" }, { v: "11s", l: "Avg. first response" }, { v: "4 wks", l: "From kickoff to live" }] },
        { tag: "E-commerce · n8n + Make", t: "Order ops automated end-to-end", m: [{ v: "0", l: "Manual handoffs" }, { v: "−87%", l: "Order errors" }, { v: "12k+", l: "Workflows / month" }] },
      ],
    },
    industries: {
      eyebrow: "Industries we serve",
      list: ["Financial services", "Manufacturing", "Insurance", "Retail & e-commerce", "Logistics", "Professional services", "Healthcare", "Media & publishing"],
    },
    testimonials: {
      eyebrow: "What partners say",
      items: [
        { q: "Velior didn't sell us Salesforce: they sold us an outcome, then delivered it three weeks early.", n: "Marco Bellini", r: "COO, mid-market manufacturer" },
        { q: "The team's depth across Salesforce, n8n and custom Python is rare. We replaced two vendors with one.", n: "Anna Rossi", r: "Head of Digital, retail group" },
        { q: "Quietly excellent. Code is clean, communication is precise, no theatre.", n: "Luca Conti", r: "CTO, SaaS scale-up" },
      ],
    },
    contact: {
      eyebrow: "Let's talk",
      title: "Tell us about your next move.",
      lede: "We'll reply within one business day with a concrete next step. No sales theatre.",
      form: {
        firstName: "First name",
        lastName: "Last name",
        company: "Company",
        email: "Work email",
        topic: "What can we help with?",
        topics: ["Salesforce", "Custom software", "AI & data", "Process automation"],
        message: "A few sentences on the project",
        submit: "Send message",
        sent: "Message received. We'll be in touch within one business day.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, Albania",
        hours: "Mon–Fri, 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "About Velior",
      title: "A European consultancy for ambitious operators.",
      lede: "Founded by engineers tired of CRM theatre, Velior delivers Salesforce, automation, and custom software with the rigor of a product team and the discretion of a private partner.",
      values: [
        { t: "Outcome over output", d: "We bill by milestone, not seat. If it doesn't move a metric you care about, we don't ship it." },
        { t: "Rigor without bureaucracy", d: "Senior engineers on every call. No layered account management between you and the people writing the code." },
        { t: "Built to be inherited", d: "Documentation, tests and runbooks come standard. We expect you'll outgrow needing us." },
      ],
      stats: [
        { v: "2025", l: "Founded" },
        { v: "15", l: "Engineers & consultants" },
        { v: "100+", l: "Salesforce certifications" },
      ],
    },
    footer: {
      tagline: "CRM, automation, and AI engineered for growth.",
      sections: [
        { t: "Company", l: [["About", "about"], ["Services", "services"], ["Contact", "contact"]] as [string, string][] },
        { t: "Capabilities", l: [["Salesforce", "services"], ["Full-stack", "services"], ["AI & agents", "services"], ["Automation", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group",
      privacy: "Privacy",
      cookies: "Cookies",
    },
    ui: {
      learnMore: "Learn more",
      caseN: "case",
      whereWeOperate: "Where we operate.",
      quietlyExcellent: "Quietly excellent.",
      buildNext: ["Let's build your", "next chapter."] as [string, string],
      operatingPrinciples: "operating principles",
      whatWeBelieve: "What we believe, in practice.",
      threePillars: ["Four pillars.", "One stack,", "shipped end-to-end."] as [string, string, string],
      pillar: "pillar",
      ambitiousOperators: ["A European consultancy for", "ambitious operators."] as [string, string],
      tellUs: ["Tell us about your", "next move."] as [string, string],
      messageReceived: "Message received.",
      techStack: "technology stack",
      techStackTitle: ["The platforms we", "deliver every quarter."] as [string, string],
      activeCerts: "active certifications",
      implementations: "closed projects",
      partnerSince: "partner since",
      contact: "Contact",
      email: "email",
      office: "office",
      hours: "hours",
      directLine: "direct line",
      howToReach: "How to reach us.",
      channelsLede: "Pick the channel that fits you. We typically reply within one business day.",
      italy: "Italy",
      albania: "Albania",
      whatsappTitle: "Chat on WhatsApp",
      whatsappSub: "Pick a country to start the conversation.",
      whatsappFoot: "Mon–Fri, 09:00–18:00 CET",
    },
    salesforce: {
      eyebrow: "Salesforce practice",
      title: "One Salesforce hub. Six disciplines.",
      lede: "From first-call advisory to long-term managed delivery: every Salesforce engagement we run sits in one of these six disciplines.",
      coreSub: "End-to-end practice",
      petals: [
        { t: "Salesforce Consulting", d: "Roadmaps, audits, architecture decisions." },
        { t: "Salesforce Implementation", d: "Sales, Service, Marketing & Data Cloud rollouts." },
        { t: "Salesforce Integration", d: "MuleSoft, REST APIs, event-driven flows." },
        { t: "Development & Customization", d: "Apex, Lightning, LWC, Flows." },
        { t: "Salesforce Migration", d: "Classic to Lightning, org consolidation, data uplift." },
        { t: "Managed Services", d: "Releases, monitoring, evolution under SLA." },
      ],
    },
  },
  it: {
    nav: {
      home: "Home",
      about: "Chi siamo",
      services: "Servizi",
      contact: "Contatti",
      cta: "Prenota una consulenza",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Albania",
      title: ["CRM, automazione e AI", "al servizio della crescita."] as [string, string],
      lede: "Aiutiamo le aziende ambiziose a trasformare l'ecosistema Salesforce, l'automazione iPaaS e lo sviluppo full-stack in ricavi misurabili.",
      ctaPrimary: "Richiedi una consulenza gratuita",
      ctaSecondary: "Scopri i nostri servizi",
      stats: [
        { v: "20+", l: "Progetti chiusi" },
        { v: "100+", l: "Certificazioni Salesforce" },
        { v: "1", l: "Sede · Tirana" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Certificati su tutta la piattaforma.",
      lede: "Da Sales Cloud ad Agentforce e Data Cloud: i nostri consulenti detengono certificazioni attive e rilasciano lavoro in produzione ogni trimestre. Velior è Salesforce Consulting Partner registrato.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "Cosa facciamo",
      title: "Quattro pilastri. Uno stack unico, consegnato end-to-end.",
      items: [
        {
          n: "01",
          t: "Salesforce",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau e Agentforce: implementati, integrati e ottimizzati per il ROI.",
          bullets: ["Implementazione & migrazione", "Sviluppo Lightning & Apex", "Reportistica & dashboard", "Agentforce & AI agents"],
        },
        {
          n: "02",
          t: "Sviluppo full-stack",
          d: "Software custom in Next.js, Node, Python e Go: costruito con lo stesso rigore delle piattaforme che integriamo.",
          bullets: ["App Next.js / Angular / Vue", "Servizi FastAPI & Node", "Postgres, Mongo, Redis", "DevOps & observability"],
        },
        {
          n: "03",
          t: "AI & agenti",
          d: "Sistemi LLM, RAG e agenti progettati per la produzione: radicati nei tuoi dati, governati e misurabili.",
          bullets: ["Pipeline LLM & RAG", "Embeddings & vector search", "Agentforce & agenti custom", "Valutazione & guardrail"],
        },
        {
          n: "04",
          t: "Process automation",
          d: "Workflow iPaaS end-to-end su n8n e Make. Eliminiamo il lavoro manuale, gli errori da copia-incolla e colleghiamo tutti i sistemi che già usi.",
          bullets: ["Workflow n8n & Make", "Orchestrazione API & webhook", "Pipeline di dati e documenti", "Monitoraggio operativo"],
        },
      ],
    },
    process: {
      eyebrow: "Come lavoriamo",
      title: "Dalla scoperta alla produzione, in passi chiari.",
      steps: [
        { n: "01", t: "Discovery", d: "Analizziamo stack, dati e processi per identificare colli di bottiglia e opportunità. Consegniamo una diagnosi scritta e una roadmap con priorità." },
        { n: "02", t: "Design", d: "Definiamo architettura della soluzione, modello dati, integrazioni e criteri di accettazione. Nulla viene costruito prima dell'approvazione di scope e risultati attesi." },
        { n: "03", t: "Implementazione", d: "Rilascio iterativo con demo periodiche e progresso trasparente. Codice pulito, revisionato e documentato in corsa: nessuna black box." },
        { n: "04", t: "Supporto", d: "Passaggio con training, runbook e SLA dedicato. Restiamo vicini per far evolvere la piattaforma con la crescita del business." },
      ],
    },
    cases: {
      eyebrow: "Lavori selezionati",
      title: "Risultati, non screenshot.",
      lede: "Alcuni progetti recenti. Nomi reali disponibili sotto NDA: contattaci per il deck completo.",
      items: [
        { tag: "Manifatturiero · Sales Cloud", t: "Pipeline unificata su 11 paesi UE", m: [{ v: "−42%", l: "Tempo di reporting" }, { v: "3.1×", l: "Velocità qualifica lead" }, { v: "€1.8M", l: "Pipeline recuperata" }] },
        { tag: "Assicurazioni · Agentforce + Data Cloud", t: "Agente AI di customer service su stack legacy", m: [{ v: "68%", l: "Ticket auto-risolti" }, { v: "11s", l: "Prima risposta media" }, { v: "4 sett.", l: "Dal via al live" }] },
        { tag: "E-commerce · n8n + Make", t: "Order ops automatizzate end-to-end", m: [{ v: "0", l: "Handoff manuali" }, { v: "−87%", l: "Errori d'ordine" }, { v: "12k+", l: "Workflow / mese" }] },
      ],
    },
    industries: {
      eyebrow: "Settori serviti",
      list: ["Servizi finanziari", "Manifatturiero", "Assicurazioni", "Retail & e-commerce", "Logistica", "Servizi professionali", "Sanità", "Media & editoria"],
    },
    testimonials: {
      eyebrow: "Cosa dicono i partner",
      items: [
        { q: "Velior non ci ha venduto Salesforce: ci ha venduto un risultato, poi l'ha consegnato tre settimane in anticipo.", n: "Marco Bellini", r: "COO, manifatturiero mid-market" },
        { q: "La profondità del team su Salesforce, n8n e Python custom è rara. Abbiamo sostituito due fornitori con uno.", n: "Anna Rossi", r: "Head of Digital, gruppo retail" },
        { q: "Eccellenza silenziosa. Codice pulito, comunicazione precisa, niente teatro.", n: "Luca Conti", r: "CTO, SaaS scale-up" },
      ],
    },
    contact: {
      eyebrow: "Parliamone",
      title: "Raccontaci la tua prossima mossa.",
      lede: "Rispondiamo entro un giorno lavorativo con un passo concreto. Niente teatro commerciale.",
      form: {
        firstName: "Nome",
        lastName: "Cognome",
        company: "Azienda",
        email: "Email aziendale",
        topic: "Su cosa possiamo aiutarti?",
        topics: ["Salesforce", "Software custom", "AI & dati", "Process automation"],
        message: "Qualche frase sul progetto",
        submit: "Invia messaggio",
        sent: "Messaggio ricevuto. Ti scriviamo entro un giorno lavorativo.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, Albania",
        hours: "Lun–Ven, 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "Chi è Velior",
      title: "Una consulenza europea per operatori ambiziosi.",
      lede: "Fondata da ingegneri stanchi del teatro CRM, Velior consegna Salesforce, automazione e software custom con il rigore di un team di prodotto e la discrezione di un partner privato.",
      values: [
        { t: "Risultato sopra l'output", d: "Fatturiamo a milestone, non a seat. Se non muove una metrica che ti interessa, non lo rilasciamo." },
        { t: "Rigore senza burocrazia", d: "Ingegneri senior in ogni call. Niente account management che si frappone tra te e chi scrive il codice." },
        { t: "Costruito per essere ereditato", d: "Documentazione, test e runbook sono inclusi. Ci aspettiamo che presto non avrai più bisogno di noi." },
      ],
      stats: [
        { v: "2025", l: "Fondata" },
        { v: "15", l: "Ingegneri & consulenti" },
        { v: "100+", l: "Certificazioni Salesforce" },
      ],
    },
    footer: {
      tagline: "CRM, automazione e AI al servizio della crescita.",
      sections: [
        { t: "Azienda", l: [["Chi siamo", "about"], ["Servizi", "services"], ["Contatti", "contact"]] as [string, string][] },
        { t: "Competenze", l: [["Salesforce", "services"], ["Full-stack", "services"], ["AI & agenti", "services"], ["Automazione", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group",
      privacy: "Privacy",
      cookies: "Cookie",
    },
    ui: {
      learnMore: "Scopri di più",
      caseN: "case",
      whereWeOperate: "Dove operiamo.",
      quietlyExcellent: "Eccellenza silenziosa.",
      buildNext: ["Costruiamo il tuo", "prossimo capitolo."] as [string, string],
      operatingPrinciples: "principi operativi",
      whatWeBelieve: "Cosa crediamo, nella pratica.",
      threePillars: ["Quattro pilastri.", "Uno stack unico,", "consegnato end-to-end."] as [string, string, string],
      pillar: "pilastro",
      ambitiousOperators: ["Una consulenza europea per", "operatori ambiziosi."] as [string, string],
      tellUs: ["Raccontaci la tua", "prossima mossa."] as [string, string],
      messageReceived: "Messaggio ricevuto.",
      techStack: "stack tecnologico",
      techStackTitle: ["Le piattaforme che", "rilasciamo ogni trimestre."] as [string, string],
      activeCerts: "certificazioni attive",
      implementations: "progetti chiusi",
      partnerSince: "partner dal",
      contact: "Contatti",
      email: "email",
      office: "sede",
      hours: "orari",
      directLine: "linea diretta",
      howToReach: "Come contattarci.",
      channelsLede: "Scegli il canale che preferisci. Rispondiamo di norma entro un giorno lavorativo.",
      italy: "Italia",
      albania: "Albania",
      whatsappTitle: "Scrivici su WhatsApp",
      whatsappSub: "Scegli il paese per iniziare la chat.",
      whatsappFoot: "Lun–Ven, 09:00–18:00 CET",
    },
    salesforce: {
      eyebrow: "Pratica Salesforce",
      title: "Un hub Salesforce. Sei discipline.",
      lede: "Dalla prima consulenza al managed delivery a lungo termine: ogni progetto Salesforce che gestiamo rientra in una di queste sei discipline.",
      coreSub: "Pratica end-to-end",
      petals: [
        { t: "Consulenza Salesforce", d: "Roadmap, audit, decisioni di architettura." },
        { t: "Implementazione Salesforce", d: "Rilasci Sales, Service, Marketing & Data Cloud." },
        { t: "Integrazione Salesforce", d: "MuleSoft, API REST, flussi event-driven." },
        { t: "Sviluppo & Customizzazione", d: "Apex, Lightning, LWC, Flow." },
        { t: "Migrazione Salesforce", d: "Da Classic a Lightning, consolidamento org, data uplift." },
        { t: "Managed Services", d: "Release, monitoraggio, evoluzione con SLA." },
      ],
    },
  },
  sq: {
    nav: {
      home: "Home",
      about: "Rreth nesh",
      services: "Shërbimet",
      contact: "Kontakt",
      cta: "Rezervo një konsultë",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Shqipëri",
      title: ["CRM, automatizim dhe AI", "të ndërtuara për rritje."] as [string, string],
      lede: "Ndihmojmë kompanitë ambicioze ta kthejnë ekosistemin Salesforce, automatizimin iPaaS dhe zhvillimin full-stack në të ardhura të matshme.",
      ctaPrimary: "Kërko një konsultë falas",
      ctaSecondary: "Eksploro shërbimet",
      stats: [
        { v: "20+", l: "Projekte të mbyllura" },
        { v: "100+", l: "Çertifikime Salesforce" },
        { v: "1", l: "Zyrë · Tirana" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Të çertifikuar në të gjithë platformën.",
      lede: "Nga Sales Cloud te Agentforce dhe Data Cloud: konsulentët tanë mbajnë çertifikime aktive dhe çojnë punë në prodhim çdo tremujor. Velior është Salesforce Consulting Partner i regjistruar.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "Çfarë bëjmë",
      title: "Katër shtylla. Një stack i vetëm, i dorëzuar end-to-end.",
      items: [
        {
          n: "01",
          t: "Salesforce",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau dhe Agentforce: të zbatuara, të integruara dhe të rregulluara për ROI.",
          bullets: ["Implementim & migrim", "Zhvillim Lightning & Apex", "Raporte & dashboard", "Agentforce & AI agents"],
        },
        {
          n: "02",
          t: "Zhvillim full-stack",
          d: "Software i dedikuar në Next.js, Node, Python dhe Go: i ndërtuar me të njëjtin rigorozitet si platformat që integrojmë.",
          bullets: ["Aplikacione Next.js / Angular / Vue", "Shërbime FastAPI & Node", "Postgres, Mongo, Redis", "DevOps & observability"],
        },
        {
          n: "03",
          t: "AI & agentë",
          d: "Sisteme LLM, RAG dhe agentë të dizajnuar për prodhim: të ankoruar në të dhënat tuaja, të qeverisur dhe të matshëm.",
          bullets: ["Pipeline LLM & RAG", "Embeddings & vector search", "Agentforce & agentë custom", "Vlerësim & guardrail"],
        },
        {
          n: "04",
          t: "Automatizim proceset",
          d: "Workflow iPaaS end-to-end në n8n dhe Make. Eliminojmë punën manuale, gabimet nga copy-paste dhe lidhim të gjitha sistemet që përdorni.",
          bullets: ["Workflow n8n & Make", "Orkestrim API & webhook", "Pipeline të dhënash dhe dokumentesh", "Monitorim operacional"],
        },
      ],
    },
    process: {
      eyebrow: "Si punojmë",
      title: "Nga zbulimi në prodhim, në hapa të qartë.",
      steps: [
        { n: "01", t: "Discovery", d: "Auditojmë stack-un, të dhënat dhe proceset për të identifikuar pengesa dhe mundësi. Ju marrim një diagnozë të shkruar dhe një roadmap të prioritizuar." },
        { n: "02", t: "Design", d: "Përcaktojmë arkitekturën e zgjidhjes, modelin e të dhënave, integrimet dhe kriteret e pranimit. Asgjë nuk ndërtohet pa miratim të scope-it dhe rezultateve." },
        { n: "03", t: "Implementim", d: "Dorëzim iterativ me demo periodike dhe progres transparent. Kod i pastër, i rishikuar dhe i dokumentuar gjatë rrugës: pa kuti të zezë." },
        { n: "04", t: "Mbështetje", d: "Kalim me trajnim, runbook dhe SLA të dedikuar. Qëndrojmë afër për ta zhvilluar platformën në sinkron me rritjen e biznesit." },
      ],
    },
    cases: {
      eyebrow: "Punë të zgjedhura",
      title: "Rezultate, jo screenshot.",
      lede: "Disa angazhime të fundit. Emrat e vërtetë në dispozicion nën NDA: na kontaktoni për deck-un e plotë.",
      items: [
        { tag: "Prodhim · Sales Cloud", t: "Pipeline e unifikuar në 11 shtete BE", m: [{ v: "−42%", l: "Kohë raportimi" }, { v: "3.1×", l: "Shpejtësi kualifikimi lead" }, { v: "€1.8M", l: "Pipeline e rikuperuar" }] },
        { tag: "Sigurime · Agentforce + Data Cloud", t: "Agjent AI customer service mbi stack legacy", m: [{ v: "68%", l: "Tikete vetë-zgjidhura" }, { v: "11s", l: "Përgjigje e parë mesatare" }, { v: "4 jav.", l: "Nga starti në live" }] },
        { tag: "E-commerce · n8n + Make", t: "Order ops të automatizuara end-to-end", m: [{ v: "0", l: "Handoff manualë" }, { v: "−87%", l: "Gabime porosish" }, { v: "12k+", l: "Workflow / muaj" }] },
      ],
    },
    industries: {
      eyebrow: "Sektorët që mbulojmë",
      list: ["Shërbime financiare", "Prodhim", "Sigurime", "Retail & e-commerce", "Logjistikë", "Shërbime profesionale", "Shëndetësi", "Media & botim"],
    },
    testimonials: {
      eyebrow: "Çfarë thonë partnerët",
      items: [
        { q: "Velior nuk na shiti Salesforce: na shiti një rezultat dhe e dorëzoi tre javë para afatit.", n: "Marco Bellini", r: "COO, prodhim mid-market" },
        { q: "Thellësia e ekipit në Salesforce, n8n dhe Python custom është e rrallë. Zëvendësuam dy furnitorë me një.", n: "Anna Rossi", r: "Head of Digital, grup retail" },
        { q: "Ekselencë në heshtje. Kod i pastër, komunikim i saktë, asnjë teatër.", n: "Luca Conti", r: "CTO, SaaS scale-up" },
      ],
    },
    contact: {
      eyebrow: "Le të flasim",
      title: "Na trego për lëvizjen tënde të radhës.",
      lede: "Përgjigjemi brenda një dite pune me një hap konkret. Pa teatër komercial.",
      form: {
        firstName: "Emri",
        lastName: "Mbiemri",
        company: "Kompania",
        email: "Email pune",
        topic: "Si mund të ndihmojmë?",
        topics: ["Salesforce", "Software custom", "AI & të dhëna", "Automatizim proceset"],
        message: "Disa fjali për projektin",
        submit: "Dërgo mesazhin",
        sent: "Mesazhi u mor. Ju kontaktojmë brenda një dite pune.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, Shqipëri",
        hours: "Hë–Pre, 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "Rreth Velior",
      title: "Një konsulencë evropiane për operatorë ambiciozë.",
      lede: "E themeluar nga inxhinierë të lodhur nga teatri i CRM-së, Velior ofron Salesforce, automatizim dhe software custom me rigorozitetin e një ekipi prodhimi dhe diskrecionin e një partneri privat.",
      values: [
        { t: "Rezultat mbi output", d: "Faturojmë sipas milestone, jo sipas seat. Nëse nuk lëviz një metrikë që ju intereson, nuk e çojmë në prodhim." },
        { t: "Rigorozitet pa burokraci", d: "Inxhinierë senior në çdo call. Pa account management i shtresuar mes jush dhe njerëzve që shkruajnë kodin." },
        { t: "Ndërtuar për t'u trashëguar", d: "Dokumentimi, testet dhe runbook vijnë standard. Presim të mos kërkoni më ndihmën tonë." },
      ],
      stats: [
        { v: "2025", l: "Themeluar" },
        { v: "15", l: "Inxhinierë & konsulentë" },
        { v: "100+", l: "Çertifikime Salesforce" },
      ],
    },
    footer: {
      tagline: "CRM, automatizim dhe AI të ndërtuara për rritje.",
      sections: [
        { t: "Kompania", l: [["Rreth nesh", "about"], ["Shërbimet", "services"], ["Kontakt", "contact"]] as [string, string][] },
        { t: "Aftësi", l: [["Salesforce", "services"], ["Full-stack", "services"], ["AI & agentë", "services"], ["Automatizim", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group",
      privacy: "Privatësia",
      cookies: "Cookie",
    },
    ui: {
      learnMore: "Mëso më shumë",
      caseN: "case",
      whereWeOperate: "Ku operojmë.",
      quietlyExcellent: "Ekselencë në heshtje.",
      buildNext: ["Le ta ndërtojmë", "kapitullin tënd të radhës."] as [string, string],
      operatingPrinciples: "parime operative",
      whatWeBelieve: "Çfarë besojmë, në praktikë.",
      threePillars: ["Katër shtylla.", "Një stack i vetëm,", "i dorëzuar end-to-end."] as [string, string, string],
      pillar: "shtyllë",
      ambitiousOperators: ["Një konsulencë evropiane për", "operatorë ambiciozë."] as [string, string],
      tellUs: ["Na trego për lëvizjen", "tënde të radhës."] as [string, string],
      messageReceived: "Mesazhi u mor.",
      techStack: "stack teknologjik",
      techStackTitle: ["Platformat që dorëzojmë", "çdo tremujor."] as [string, string],
      activeCerts: "çertifikime aktive",
      implementations: "projekte të mbyllura",
      partnerSince: "partner që nga",
      contact: "Kontakt",
      email: "email",
      office: "zyrë",
      hours: "orare",
      directLine: "linjë e drejtpërdrejtë",
      howToReach: "Si të na kontaktoni.",
      channelsLede: "Zgjidhni kanalin që ju përshtatet. Përgjigjemi normalisht brenda një dite pune.",
      italy: "Itali",
      albania: "Shqipëri",
      whatsappTitle: "Shkruaj në WhatsApp",
      whatsappSub: "Zgjidh shtetin për të nisur bisedën.",
      whatsappFoot: "Hë–Pre, 09:00–18:00 CET",
    },
    salesforce: {
      eyebrow: "Praktika Salesforce",
      title: "Një hub Salesforce. Gjashtë disiplina.",
      lede: "Nga konsulta e parë te managed delivery afatgjatë: çdo angazhim Salesforce që drejtojmë hyn në një nga këto gjashtë disiplina.",
      coreSub: "Praktikë end-to-end",
      petals: [
        { t: "Konsulencë Salesforce", d: "Roadmap, audit, vendime arkitekturore." },
        { t: "Implementim Salesforce", d: "Hapje Sales, Service, Marketing & Data Cloud." },
        { t: "Integrim Salesforce", d: "MuleSoft, API REST, rrjedha event-driven." },
        { t: "Zhvillim & Customizim", d: "Apex, Lightning, LWC, Flow." },
        { t: "Migrim Salesforce", d: "Nga Classic te Lightning, konsolidim org, data uplift." },
        { t: "Managed Services", d: "Release, monitorim, evolucion me SLA." },
      ],
    },
  },
  de: {
    nav: {
      home: "Home",
      about: "Über uns",
      services: "Leistungen",
      contact: "Kontakt",
      cta: "Beratung buchen",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Schweiz",
      title: ["CRM, Automatisierung und KI", "für nachhaltiges Wachstum."] as [string, string],
      lede: "Wir helfen ambitionierten Unternehmen, das Salesforce-Ökosystem, iPaaS-Automatisierung und Full-Stack-Engineering in messbaren Umsatz zu verwandeln.",
      ctaPrimary: "Kostenlose Beratung anfordern",
      ctaSecondary: "Leistungen entdecken",
      stats: [
        { v: "20+", l: "Abgeschlossene Projekte" },
        { v: "100+", l: "Salesforce-Zertifizierungen" },
        { v: "1", l: "Standort · Tirana" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Plattformweit zertifiziert.",
      lede: "Von Sales Cloud bis Agentforce und Data Cloud: unsere Berater haben aktive Zertifizierungen und liefern jedes Quartal Produktion. Velior ist registrierter Salesforce Consulting Partner.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "Was wir tun",
      title: "Vier Säulen. Ein Stack, durchgängig geliefert.",
      items: [
        {
          n: "01",
          t: "Salesforce",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau und Agentforce: implementiert, integriert und auf ROI optimiert.",
          bullets: ["Implementierung & Migration", "Lightning- & Apex-Entwicklung", "Reporting & Dashboards", "Agentforce & KI-Agenten"],
        },
        {
          n: "02",
          t: "Full-Stack-Entwicklung",
          d: "Custom-Software in Next.js, Node, Python und Go: gebaut mit derselben Sorgfalt wie die Plattformen, die wir integrieren.",
          bullets: ["Next.js / Angular / Vue Apps", "FastAPI- & Node-Services", "Postgres, Mongo, Redis", "DevOps & Observability"],
        },
        {
          n: "03",
          t: "KI & Agenten",
          d: "LLM-, RAG- und Agentensysteme für die Produktion: in Ihren Daten verankert, governed und messbar.",
          bullets: ["LLM- & RAG-Pipelines", "Embeddings & Vektorsuche", "Agentforce & Custom Agents", "Evaluation & Guardrails"],
        },
        {
          n: "04",
          t: "Prozessautomatisierung",
          d: "End-to-End iPaaS-Workflows auf n8n und Make. Wir eliminieren manuelle Arbeit, Copy-Paste-Fehler und verbinden alle Systeme, die Sie bereits nutzen.",
          bullets: ["n8n- & Make-Workflows", "API- & Webhook-Orchestrierung", "Daten- & Dokumenten-Pipelines", "Operatives Monitoring"],
        },
      ],
    },
    process: {
      eyebrow: "Wie wir arbeiten",
      title: "Von Discovery bis Produktion, in klaren Schritten.",
      steps: [
        { n: "01", t: "Discovery", d: "Wir auditieren Stack, Daten und Prozesse, um Engpässe und Chancen zu identifizieren. Sie erhalten eine schriftliche Diagnose und eine priorisierte Roadmap." },
        { n: "02", t: "Design", d: "Wir definieren Lösungsarchitektur, Datenmodell, Integrationen und Akzeptanzkriterien. Nichts wird gebaut, bevor Scope und Ergebnisse abgesegnet sind." },
        { n: "03", t: "Implementierung", d: "Iterative Auslieferung mit regelmäßigen Demos und transparentem Fortschritt. Sauberer Code, dokumentiert während wir liefern: keine Black Boxes." },
        { n: "04", t: "Support", d: "Übergabe mit Schulung, Runbooks und dediziertem SLA. Wir bleiben dran, damit die Plattform mit Ihrem Geschäft wächst." },
      ],
    },
    cases: {
      eyebrow: "Ausgewählte Arbeiten",
      title: "Ergebnisse, keine Screenshots.",
      lede: "Einige aktuelle Projekte. Echte Namen unter NDA verfügbar: kontaktieren Sie uns für das vollständige Deck.",
      items: [
        { tag: "Fertigung · Sales Cloud", t: "Einheitliche Pipeline über 11 EU-Länder", m: [{ v: "−42%", l: "Reporting-Zeit" }, { v: "3.1×", l: "Lead-Qualifizierungstempo" }, { v: "€1.8M", l: "Wiederhergestellte Pipeline" }] },
        { tag: "Versicherung · Agentforce + Data Cloud", t: "KI-Agent für Customer Service auf Legacy-Stack", m: [{ v: "68%", l: "Tickets automatisch gelöst" }, { v: "11s", l: "Erste Antwort im Schnitt" }, { v: "4 Wo.", l: "Vom Kickoff zum Live" }] },
        { tag: "E-Commerce · n8n + Make", t: "Order-Operations end-to-end automatisiert", m: [{ v: "0", l: "Manuelle Übergaben" }, { v: "−87%", l: "Bestellfehler" }, { v: "12k+", l: "Workflows / Monat" }] },
      ],
    },
    industries: {
      eyebrow: "Branchen, die wir bedienen",
      list: ["Finanzdienstleistungen", "Fertigung", "Versicherungen", "Retail & E-Commerce", "Logistik", "Professional Services", "Gesundheitswesen", "Medien & Verlag"],
    },
    testimonials: {
      eyebrow: "Was Partner sagen",
      items: [
        { q: "Velior hat uns nicht Salesforce verkauft: man hat uns ein Ergebnis verkauft und es drei Wochen früher geliefert.", n: "Marco Bellini", r: "COO, Mid-Market-Fertigung" },
        { q: "Die Tiefe des Teams in Salesforce, n8n und Custom-Python ist selten. Wir haben zwei Anbieter durch einen ersetzt.", n: "Anna Rossi", r: "Head of Digital, Retail-Gruppe" },
        { q: "Stille Exzellenz. Sauberer Code, präzise Kommunikation, kein Theater.", n: "Luca Conti", r: "CTO, SaaS-Scale-up" },
      ],
    },
    contact: {
      eyebrow: "Sprechen wir",
      title: "Erzählen Sie uns von Ihrem nächsten Schritt.",
      lede: "Wir antworten innerhalb eines Werktags mit einem konkreten nächsten Schritt. Kein Sales-Theater.",
      form: {
        firstName: "Vorname",
        lastName: "Nachname",
        company: "Unternehmen",
        email: "Geschäftliche E-Mail",
        topic: "Wobei können wir helfen?",
        topics: ["Salesforce", "Custom-Software", "KI & Daten", "Prozessautomatisierung"],
        message: "Ein paar Sätze zum Projekt",
        submit: "Nachricht senden",
        sent: "Nachricht erhalten. Wir melden uns innerhalb eines Werktags.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, Albanien",
        hours: "Mo–Fr, 09:00–18:00 MEZ",
      },
    },
    about: {
      eyebrow: "Über Velior",
      title: "Eine europäische Beratung für ambitionierte Operatoren.",
      lede: "Gegründet von Ingenieuren, die genug vom CRM-Theater haben. Velior liefert Salesforce, Automatisierung und Custom-Software mit der Sorgfalt eines Produktteams und der Diskretion eines privaten Partners.",
      values: [
        { t: "Ergebnis vor Output", d: "Wir rechnen nach Milestones ab, nicht pro Seat. Wenn es keine Metrik bewegt, die Ihnen wichtig ist, liefern wir es nicht aus." },
        { t: "Sorgfalt ohne Bürokratie", d: "Senior-Ingenieure in jedem Call. Kein Account-Management zwischen Ihnen und den Leuten, die den Code schreiben." },
        { t: "Gebaut zum Übernehmen", d: "Dokumentation, Tests und Runbooks gehören dazu. Wir gehen davon aus, dass Sie uns irgendwann nicht mehr brauchen." },
      ],
      stats: [
        { v: "2025", l: "Gegründet" },
        { v: "15", l: "Ingenieure & Berater" },
        { v: "100+", l: "Salesforce-Zertifizierungen" },
      ],
    },
    footer: {
      tagline: "CRM, Automatisierung und KI für nachhaltiges Wachstum.",
      sections: [
        { t: "Unternehmen", l: [["Über uns", "about"], ["Leistungen", "services"], ["Kontakt", "contact"]] as [string, string][] },
        { t: "Kompetenzen", l: [["Salesforce", "services"], ["Full-Stack", "services"], ["KI & Agenten", "services"], ["Automatisierung", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group",
      privacy: "Datenschutz",
      cookies: "Cookies",
    },
    ui: {
      learnMore: "Mehr erfahren",
      caseN: "case",
      whereWeOperate: "Wo wir tätig sind.",
      quietlyExcellent: "Stille Exzellenz.",
      buildNext: ["Lassen Sie uns Ihr", "nächstes Kapitel bauen."] as [string, string],
      operatingPrinciples: "leitprinzipien",
      whatWeBelieve: "Woran wir glauben, in der Praxis.",
      threePillars: ["Vier Säulen.", "Ein Stack,", "durchgängig geliefert."] as [string, string, string],
      pillar: "Säule",
      ambitiousOperators: ["Eine europäische Beratung für", "ambitionierte Operatoren."] as [string, string],
      tellUs: ["Erzählen Sie uns von", "Ihrem nächsten Schritt."] as [string, string],
      messageReceived: "Nachricht erhalten.",
      techStack: "tech stack",
      techStackTitle: ["Die Plattformen,", "die wir jedes Quartal liefern."] as [string, string],
      activeCerts: "aktive Zertifizierungen",
      implementations: "abgeschlossene Projekte",
      partnerSince: "Partner seit",
      contact: "Kontakt",
      email: "E-Mail",
      office: "Standort",
      hours: "Zeiten",
      directLine: "direkte Linie",
      howToReach: "So erreichen Sie uns.",
      channelsLede: "Wählen Sie den Kanal, der zu Ihnen passt. Wir antworten in der Regel innerhalb eines Werktags.",
      italy: "Italien",
      albania: "Albanien",
      whatsappTitle: "Auf WhatsApp schreiben",
      whatsappSub: "Wählen Sie ein Land, um zu starten.",
      whatsappFoot: "Mo–Fr, 09:00–18:00 MEZ",
    },
    salesforce: {
      eyebrow: "Salesforce-Praxis",
      title: "Ein Salesforce-Hub. Sechs Disziplinen.",
      lede: "Vom ersten Beratungsgespräch bis zum langfristigen Managed Delivery: jedes Salesforce-Projekt fällt in eine dieser sechs Disziplinen.",
      coreSub: "End-to-End-Praxis",
      petals: [
        { t: "Salesforce Consulting", d: "Roadmaps, Audits, Architekturentscheidungen." },
        { t: "Salesforce Implementation", d: "Sales-, Service-, Marketing- und Data-Cloud-Rollouts." },
        { t: "Salesforce Integration", d: "MuleSoft, REST-APIs, event-driven Flows." },
        { t: "Development & Customization", d: "Apex, Lightning, LWC, Flows." },
        { t: "Salesforce Migration", d: "Classic zu Lightning, Org-Konsolidierung, Data Uplift." },
        { t: "Managed Services", d: "Releases, Monitoring, Evolution unter SLA." },
      ],
    },
  },
  fr: {
    nav: {
      home: "Home",
      about: "À propos",
      services: "Services",
      contact: "Contact",
      cta: "Réserver une consultation",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Suisse",
      title: ["CRM, automatisation et IA", "au service de votre croissance."] as [string, string],
      lede: "Nous aidons les entreprises ambitieuses à transformer l'écosystème Salesforce, l'automatisation iPaaS et le développement full-stack en revenus mesurables.",
      ctaPrimary: "Demander une consultation gratuite",
      ctaSecondary: "Découvrir nos services",
      stats: [
        { v: "20+", l: "Projets livrés" },
        { v: "100+", l: "Certifications Salesforce" },
        { v: "1", l: "Bureau · Tirana" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Certifiés sur toute la plateforme.",
      lede: "De Sales Cloud à Agentforce et Data Cloud : nos consultants détiennent des certifications actives et livrent en production chaque trimestre. Velior est Salesforce Consulting Partner enregistré.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "Ce que nous faisons",
      title: "Quatre piliers. Une stack, livrée de bout en bout.",
      items: [
        {
          n: "01",
          t: "Salesforce",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau et Agentforce : implémentés, intégrés et optimisés pour le ROI.",
          bullets: ["Implémentation & migration", "Développement Lightning & Apex", "Reporting & dashboards", "Agentforce & agents IA"],
        },
        {
          n: "02",
          t: "Développement full-stack",
          d: "Logiciels sur mesure en Next.js, Node, Python et Go : construits avec la même rigueur que les plateformes que nous intégrons.",
          bullets: ["Apps Next.js / Angular / Vue", "Services FastAPI & Node", "Postgres, Mongo, Redis", "DevOps & observabilité"],
        },
        {
          n: "03",
          t: "IA & agents",
          d: "Systèmes LLM, RAG et agents conçus pour la production : ancrés dans vos données, gouvernés et mesurables.",
          bullets: ["Pipelines LLM & RAG", "Embeddings & recherche vectorielle", "Agentforce & agents sur mesure", "Évaluation & garde-fous"],
        },
        {
          n: "04",
          t: "Automatisation des processus",
          d: "Workflows iPaaS de bout en bout sur n8n et Make. Nous éliminons le travail manuel, les erreurs de copier-coller et connectons tous vos systèmes.",
          bullets: ["Workflows n8n & Make", "Orchestration API & webhooks", "Pipelines de données et documents", "Supervision opérationnelle"],
        },
      ],
    },
    process: {
      eyebrow: "Comment nous travaillons",
      title: "De la découverte à la production, en étapes claires.",
      steps: [
        { n: "01", t: "Discovery", d: "Nous auditons votre stack, vos données et vos processus pour identifier les goulots et les opportunités. Vous recevez un diagnostic écrit et une feuille de route priorisée." },
        { n: "02", t: "Design", d: "Nous définissons l'architecture, le modèle de données, les intégrations et les critères d'acceptation. Rien ne se construit avant validation du périmètre et des résultats attendus." },
        { n: "03", t: "Implémentation", d: "Livraison itérative avec démos régulières et progrès transparent. Code propre, revu et documenté en continu : pas de boîte noire." },
        { n: "04", t: "Support", d: "Transmission avec formation, runbooks et SLA dédié. Nous restons proches pour faire évoluer la plateforme avec votre activité." },
      ],
    },
    cases: {
      eyebrow: "Travaux sélectionnés",
      title: "Des résultats, pas des captures d'écran.",
      lede: "Quelques projets récents. Vrais noms disponibles sous NDA : contactez-nous pour le deck complet.",
      items: [
        { tag: "Industrie · Sales Cloud", t: "Pipeline unifiée sur 11 pays UE", m: [{ v: "−42%", l: "Temps de reporting" }, { v: "3.1×", l: "Vitesse de qualification leads" }, { v: "€1.8M", l: "Pipeline récupérée" }] },
        { tag: "Assurance · Agentforce + Data Cloud", t: "Agent IA service client sur stack legacy", m: [{ v: "68%", l: "Tickets résolus en auto" }, { v: "11s", l: "Première réponse moyenne" }, { v: "4 sem.", l: "Du kickoff au live" }] },
        { tag: "E-commerce · n8n + Make", t: "Order ops automatisées de bout en bout", m: [{ v: "0", l: "Handoffs manuels" }, { v: "−87%", l: "Erreurs de commande" }, { v: "12k+", l: "Workflows / mois" }] },
      ],
    },
    industries: {
      eyebrow: "Secteurs servis",
      list: ["Services financiers", "Industrie", "Assurance", "Retail & e-commerce", "Logistique", "Services professionnels", "Santé", "Médias & édition"],
    },
    testimonials: {
      eyebrow: "Ce que disent les partenaires",
      items: [
        { q: "Velior ne nous a pas vendu Salesforce : ils nous ont vendu un résultat, et l'ont livré trois semaines en avance.", n: "Marco Bellini", r: "COO, industriel mid-market" },
        { q: "La profondeur de l'équipe sur Salesforce, n8n et Python sur mesure est rare. Nous avons remplacé deux prestataires par un seul.", n: "Anna Rossi", r: "Head of Digital, groupe retail" },
        { q: "Excellence silencieuse. Code propre, communication précise, aucun théâtre.", n: "Luca Conti", r: "CTO, SaaS scale-up" },
      ],
    },
    contact: {
      eyebrow: "Parlons-en",
      title: "Parlez-nous de votre prochaine étape.",
      lede: "Nous répondons sous un jour ouvré avec une étape concrète. Pas de théâtre commercial.",
      form: {
        firstName: "Prénom",
        lastName: "Nom",
        company: "Entreprise",
        email: "E-mail professionnel",
        topic: "Sur quoi pouvons-nous aider ?",
        topics: ["Salesforce", "Logiciel sur mesure", "IA & données", "Automatisation"],
        message: "Quelques phrases sur le projet",
        submit: "Envoyer le message",
        sent: "Message reçu. Nous revenons vers vous sous un jour ouvré.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, Albanie",
        hours: "Lun–Ven, 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "À propos de Velior",
      title: "Un cabinet de conseil européen pour opérateurs ambitieux.",
      lede: "Fondé par des ingénieurs lassés du théâtre CRM, Velior livre Salesforce, automatisation et logiciels sur mesure avec la rigueur d'une équipe produit et la discrétion d'un partenaire privé.",
      values: [
        { t: "Le résultat avant l'output", d: "Nous facturons par jalon, pas au siège. Si ça ne bouge pas une métrique qui compte pour vous, on ne le livre pas." },
        { t: "Rigueur sans bureaucratie", d: "Des ingénieurs senior à chaque appel. Pas d'account management entre vous et ceux qui écrivent le code." },
        { t: "Construit pour être hérité", d: "Documentation, tests et runbooks fournis d'office. Nous nous attendons à ce que vous n'ayez plus besoin de nous." },
      ],
      stats: [
        { v: "2025", l: "Fondé" },
        { v: "15", l: "Ingénieurs & consultants" },
        { v: "100+", l: "Certifications Salesforce" },
      ],
    },
    footer: {
      tagline: "CRM, automatisation et IA au service de votre croissance.",
      sections: [
        { t: "Société", l: [["À propos", "about"], ["Services", "services"], ["Contact", "contact"]] as [string, string][] },
        { t: "Compétences", l: [["Salesforce", "services"], ["Full-stack", "services"], ["IA & agents", "services"], ["Automatisation", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group",
      privacy: "Confidentialité",
      cookies: "Cookies",
    },
    ui: {
      learnMore: "En savoir plus",
      caseN: "case",
      whereWeOperate: "Là où nous opérons.",
      quietlyExcellent: "Excellence discrète.",
      buildNext: ["Construisons votre", "prochain chapitre."] as [string, string],
      operatingPrinciples: "principes opératoires",
      whatWeBelieve: "Ce que nous croyons, en pratique.",
      threePillars: ["Quatre piliers.", "Une stack,", "livrée de bout en bout."] as [string, string, string],
      pillar: "pilier",
      ambitiousOperators: ["Un cabinet de conseil européen pour", "opérateurs ambitieux."] as [string, string],
      tellUs: ["Parlez-nous de votre", "prochaine étape."] as [string, string],
      messageReceived: "Message reçu.",
      techStack: "stack technologique",
      techStackTitle: ["Les plateformes que", "nous livrons chaque trimestre."] as [string, string],
      activeCerts: "certifications actives",
      implementations: "projets livrés",
      partnerSince: "partenaire depuis",
      contact: "Contact",
      email: "e-mail",
      office: "bureau",
      hours: "horaires",
      directLine: "ligne directe",
      howToReach: "Comment nous joindre.",
      channelsLede: "Choisissez le canal qui vous convient. Nous répondons généralement sous un jour ouvré.",
      italy: "Italie",
      albania: "Albanie",
      whatsappTitle: "Écrire sur WhatsApp",
      whatsappSub: "Choisissez un pays pour démarrer.",
      whatsappFoot: "Lun–Ven, 09:00–18:00 CET",
    },
    salesforce: {
      eyebrow: "Pratique Salesforce",
      title: "Un hub Salesforce. Six disciplines.",
      lede: "Du premier conseil au managed delivery long terme : chaque mission Salesforce que nous menons relève de l'une de ces six disciplines.",
      coreSub: "Pratique de bout en bout",
      petals: [
        { t: "Conseil Salesforce", d: "Feuilles de route, audits, décisions d'architecture." },
        { t: "Implémentation Salesforce", d: "Déploiements Sales, Service, Marketing & Data Cloud." },
        { t: "Intégration Salesforce", d: "MuleSoft, APIs REST, flux event-driven." },
        { t: "Développement & Personnalisation", d: "Apex, Lightning, LWC, Flows." },
        { t: "Migration Salesforce", d: "Classic vers Lightning, consolidation d'org, data uplift." },
        { t: "Managed Services", d: "Releases, supervision, évolution sous SLA." },
      ],
    },
  },
  ar: {
    nav: {
      home: "الرئيسية",
      about: "من نحن",
      services: "الخدمات",
      contact: "اتصل بنا",
      cta: "احجز استشارة",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · ألبانيا",
      title: ["CRM والأتمتة والذكاء الاصطناعي", "مبنية للنمو."] as [string, string],
      lede: "نساعد الشركات الطموحة على تحويل منظومة Salesforce وأتمتة iPaaS وتطوير الـ full-stack إلى عائدات قابلة للقياس.",
      ctaPrimary: "احجز استشارة مجانية",
      ctaSecondary: "اكتشف خدماتنا",
      stats: [
        { v: "+20", l: "مشاريع مكتملة" },
        { v: "+100", l: "شهادات Salesforce" },
        { v: "1", l: "مكتب · تيرانا" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "معتمدون عبر المنصة بالكامل.",
      lede: "من Sales Cloud إلى Agentforce و Data Cloud: مستشارونا يحملون شهادات نشطة ويسلّمون الإنتاج كل ربع سنة. Velior شريك Salesforce Consulting Partner مسجّل.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "ما نقوم به",
      title: "أربع ركائز. منظومة واحدة، تُسلَّم من البداية إلى النهاية.",
      items: [
        {
          n: "01",
          t: "Salesforce",
          d: "Sales Cloud و Service Cloud و Marketing Cloud و Data Cloud و Tableau و Agentforce: مُنفَّذة ومُدمَجة ومُحسَّنة لعائد الاستثمار.",
          bullets: ["التطبيق والترحيل", "تطوير Lightning و Apex", "التقارير ولوحات البيانات", "Agentforce ووكلاء AI"],
        },
        {
          n: "02",
          t: "تطوير Full-stack",
          d: "برمجيات مخصصة في Next.js و Node و Python و Go: مبنية بنفس صرامة المنصات التي ندمجها.",
          bullets: ["تطبيقات Next.js / Angular / Vue", "خدمات FastAPI و Node", "Postgres و Mongo و Redis", "DevOps والمراقبة"],
        },
        {
          n: "03",
          t: "الذكاء الاصطناعي والوكلاء",
          d: "أنظمة LLM و RAG ووكلاء مصممة للإنتاج: مرتكزة على بياناتك، محوكمة وقابلة للقياس.",
          bullets: ["خطوط أنابيب LLM و RAG", "Embeddings والبحث المتجهي", "Agentforce ووكلاء مخصصون", "التقييم والحواجز"],
        },
        {
          n: "04",
          t: "أتمتة العمليات",
          d: "تدفقات iPaaS من البداية للنهاية على n8n و Make. نُلغي العمل اليدوي وأخطاء النسخ واللصق ونربط جميع الأنظمة التي تستخدمها.",
          bullets: ["تدفقات n8n و Make", "تنسيق API و Webhooks", "خطوط البيانات والمستندات", "المراقبة التشغيلية"],
        },
      ],
    },
    process: {
      eyebrow: "كيف نعمل",
      title: "من الاستكشاف إلى الإنتاج، في خطوات واضحة.",
      steps: [
        { n: "01", t: "Discovery", d: "نُدقّق منظومتك وبياناتك وعملياتك لتحديد العقبات والفرص. تستلم تشخيصاً مكتوباً وخارطة طريق مرتبة حسب الأولوية." },
        { n: "02", t: "Design", d: "نُحدّد بنية الحل ونموذج البيانات والتكاملات ومعايير القبول. لا يُبنى شيء قبل التوقيع على النطاق والنتائج." },
        { n: "03", t: "التنفيذ", d: "تسليم تكراري بعروض دورية وتقدم شفاف. كود نظيف ومُراجَع ومُوثَّق أثناء التنفيذ: لا توجد صناديق سوداء." },
        { n: "04", t: "الدعم", d: "تسليم مع تدريب وأدلة تشغيل و SLA مخصص. نبقى قريبين لتطوير المنصة مع نمو عملك." },
      ],
    },
    cases: {
      eyebrow: "أعمال مختارة",
      title: "نتائج، لا لقطات شاشة.",
      lede: "بعض المشاريع الأخيرة. الأسماء الحقيقية متاحة بموجب اتفاقية NDA: تواصل معنا للملف الكامل.",
      items: [
        { tag: "تصنيع · Sales Cloud", t: "خط أنابيب موحّد عبر 11 دولة أوروبية", m: [{ v: "−42%", l: "وقت التقارير" }, { v: "3.1×", l: "سرعة تأهيل العملاء المحتملين" }, { v: "€1.8M", l: "خط أنابيب مُستعاد" }] },
        { tag: "تأمين · Agentforce + Data Cloud", t: "وكيل AI لخدمة العملاء على منظومة قديمة", m: [{ v: "68%", l: "تذاكر مُحلَّلة تلقائياً" }, { v: "11s", l: "متوسط الرد الأول" }, { v: "4 أسابيع", l: "من البداية للإطلاق" }] },
        { tag: "تجارة إلكترونية · n8n + Make", t: "عمليات الطلبات مؤتمتة من البداية للنهاية", m: [{ v: "0", l: "تسليمات يدوية" }, { v: "−87%", l: "أخطاء الطلبات" }, { v: "+12k", l: "تدفقات / شهر" }] },
      ],
    },
    industries: {
      eyebrow: "القطاعات التي نخدمها",
      list: ["الخدمات المالية", "التصنيع", "التأمين", "التجزئة والتجارة الإلكترونية", "الخدمات اللوجستية", "الخدمات المهنية", "الرعاية الصحية", "الإعلام والنشر"],
    },
    testimonials: {
      eyebrow: "ما يقوله الشركاء",
      items: [
        { q: "Velior لم تَبِعنا Salesforce: باعتنا نتيجة، ثم سلّمتها قبل ثلاثة أسابيع من الموعد.", n: "Marco Bellini", r: "COO، تصنيع متوسط الحجم" },
        { q: "عمق الفريق في Salesforce و n8n و Python المخصص نادر. استبدلنا اثنين من المورّدين بواحد.", n: "Anna Rossi", r: "Head of Digital، مجموعة تجزئة" },
        { q: "تميّز هادئ. كود نظيف، تواصل دقيق، بلا مسرحيات.", n: "Luca Conti", r: "CTO، شركة SaaS ناشئة" },
      ],
    },
    contact: {
      eyebrow: "لنتحدث",
      title: "حدّثنا عن خطوتك التالية.",
      lede: "نرد خلال يوم عمل واحد بخطوة محددة. لا مسرحيات تجارية.",
      form: {
        firstName: "الاسم الأول",
        lastName: "اسم العائلة",
        company: "الشركة",
        email: "البريد المهني",
        topic: "كيف يمكننا المساعدة؟",
        topics: ["Salesforce", "برمجيات مخصصة", "AI والبيانات", "أتمتة العمليات"],
        message: "بضع جمل عن المشروع",
        submit: "إرسال الرسالة",
        sent: "تم استلام الرسالة. سنتواصل معك خلال يوم عمل واحد.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "تيرانا، ألبانيا",
        hours: "الإثنين–الجمعة، 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "عن Velior",
      title: "استشارة أوروبية للمشغلين الطموحين.",
      lede: "أُسست من قِبَل مهندسين سئموا من مسرحية CRM. تُقدّم Velior خدمات Salesforce والأتمتة والبرمجيات المخصصة بصرامة فريق منتج وحصافة شريك خاص.",
      values: [
        { t: "النتيجة فوق المُخرجات", d: "نُفوتر حسب المراحل، لا حسب المقعد. إن لم تُحرّك مقياساً يهمك، لا نُسلّمها." },
        { t: "صرامة بلا بيروقراطية", d: "مهندسون كبار في كل مكالمة. لا إدارة حسابات بينك ومن يكتبون الكود." },
        { t: "مُصمَّمة لتُورَّث", d: "التوثيق والاختبارات وأدلة التشغيل قياسية. نتوقع أن تتجاوز الحاجة إلينا." },
      ],
      stats: [
        { v: "2025", l: "تأسست" },
        { v: "15", l: "مهندسون ومستشارون" },
        { v: "+100", l: "شهادات Salesforce" },
      ],
    },
    footer: {
      tagline: "CRM والأتمتة والذكاء الاصطناعي مبنية للنمو.",
      sections: [
        { t: "الشركة", l: [["من نحن", "about"], ["الخدمات", "services"], ["اتصل بنا", "contact"]] as [string, string][] },
        { t: "القدرات", l: [["Salesforce", "services"], ["Full-stack", "services"], ["AI ووكلاء", "services"], ["الأتمتة", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group",
      privacy: "الخصوصية",
      cookies: "Cookies",
    },
    ui: {
      learnMore: "اعرف المزيد",
      caseN: "case",
      whereWeOperate: "أين نعمل.",
      quietlyExcellent: "تميّز هادئ.",
      buildNext: ["لنبنِ", "فصلك التالي."] as [string, string],
      operatingPrinciples: "مبادئ التشغيل",
      whatWeBelieve: "ما نؤمن به، تطبيقياً.",
      threePillars: ["أربع ركائز.", "منظومة واحدة،", "تُسلَّم من البداية إلى النهاية."] as [string, string, string],
      pillar: "ركيزة",
      ambitiousOperators: ["استشارة أوروبية", "للمشغلين الطموحين."] as [string, string],
      tellUs: ["حدّثنا عن", "خطوتك التالية."] as [string, string],
      messageReceived: "تم استلام الرسالة.",
      techStack: "المنظومة التقنية",
      techStackTitle: ["المنصات التي", "نُسلّمها كل ربع سنة."] as [string, string],
      activeCerts: "شهادات نشطة",
      implementations: "مشاريع مكتملة",
      partnerSince: "شريك منذ",
      contact: "اتصل بنا",
      email: "البريد",
      office: "المكتب",
      hours: "الساعات",
      directLine: "خط مباشر",
      howToReach: "كيف تتواصل معنا.",
      channelsLede: "اختر القناة التي تناسبك. عادة نرد خلال يوم عمل واحد.",
      italy: "إيطاليا",
      albania: "ألبانيا",
      whatsappTitle: "تواصل عبر WhatsApp",
      whatsappSub: "اختر البلد لبدء المحادثة.",
      whatsappFoot: "الإثنين–الجمعة، 09:00–18:00 CET",
    },
    salesforce: {
      eyebrow: "ممارسة Salesforce",
      title: "مركز Salesforce واحد. ست تخصصات.",
      lede: "من الاستشارة الأولى إلى التسليم المُدار طويل الأمد: كل مشروع Salesforce نديره يقع ضمن إحدى هذه التخصصات الستة.",
      coreSub: "ممارسة شاملة",
      petals: [
        { t: "استشارات Salesforce", d: "خرائط طريق، تدقيق، قرارات معمارية." },
        { t: "تطبيق Salesforce", d: "نشر Sales و Service و Marketing و Data Cloud." },
        { t: "تكامل Salesforce", d: "MuleSoft و REST APIs وتدفقات event-driven." },
        { t: "التطوير والتخصيص", d: "Apex و Lightning و LWC و Flows." },
        { t: "ترحيل Salesforce", d: "من Classic إلى Lightning، توحيد المنظمات، رفع البيانات." },
        { t: "Managed Services", d: "إصدارات، مراقبة، تطور بموجب SLA." },
      ],
    },
  },
} as const;
