export type Lang = "en" | "it";

export type Copy = (typeof COPY)[Lang];

export const COPY = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      contact: "Contact",
      cta: "Book a consultation",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Albania & Estonia",
      title: ["CRM, automation, and AI", "engineered for growth."] as [string, string],
      lede: "We help ambitious companies turn the Salesforce ecosystem, iPaaS automation, and full-stack engineering into measurable revenue.",
      ctaPrimary: "Book a free consultation",
      ctaSecondary: "Explore our services",
      stats: [
        { v: "30+", l: "Salesforce implementations" },
        { v: "130+", l: "Salesforce certifications" },
        { v: "40%", l: "Avg. ops time reclaimed" },
        { v: "2", l: "Offices · Tirana & Tallinn" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Certified across the platform.",
      lede: "From Sales Cloud to Agentforce and Data Cloud — our consultants hold active certifications and ship production work every quarter. Velior is a registered Salesforce Consulting Partner.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "What we do",
      title: "Four pillars. One operating system for your business.",
      items: [
        {
          n: "01",
          t: "Salesforce ecosystem",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau and Agentforce — implemented, integrated, and tuned for ROI.",
          bullets: ["Implementation & migration", "Lightning & Apex development", "Reporting & dashboards", "Agentforce & AI agents"],
        },
        {
          n: "02",
          t: "Full-stack engineering",
          d: "Custom software in Next.js, Node, Python and Go — built with the same rigour as the platforms we integrate.",
          bullets: ["Next.js / Angular / Vue apps", "FastAPI & Node services", "Postgres, Mongo, Redis", "DevOps & observability"],
        },
        {
          n: "03",
          t: "AI & agents",
          d: "LLM, RAG and agent systems engineered for production — grounded in your data, governed, and measurable.",
          bullets: ["LLM & RAG pipelines", "Embeddings & vector search", "Agentforce & custom agents", "Evaluation & guardrails"],
        },
        {
          n: "04",
          t: "Process automation",
          d: "End-to-end iPaaS workflows on n8n and Make. We retire manual work, eliminate copy-paste errors, and connect every system you already pay for.",
          bullets: ["n8n & Make workflows", "API & webhook orchestration", "Document & data pipelines", "Operational monitoring"],
        },
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "From discovery to production, in clear steps.",
      steps: [
        { n: "01", t: "Discovery", d: "We audit your stack, data, and processes to identify bottlenecks and opportunities. You receive a written diagnosis and a prioritised roadmap." },
        { n: "02", t: "Design", d: "We define solution architecture, data model, integrations, and acceptance criteria. Nothing gets built before scope and outcomes are signed off." },
        { n: "03", t: "Implement", d: "Iterative delivery with regular demos and transparent progress. Clean code, reviewed and documented as we go — no black boxes." },
        { n: "04", t: "Support", d: "Hand-off with training, runbooks, and a dedicated SLA. We stay close to evolve the platform as your business grows." },
      ],
    },
    cases: {
      eyebrow: "Selected work",
      title: "Outcomes, not screenshots.",
      lede: "A few recent engagements. Real names available under NDA — get in touch for the full deck.",
      items: [
        { tag: "Manufacturing · Sales Cloud", t: "Unified pipeline across 11 EU countries", m: [{ v: "−42%", l: "Reporting time" }, { v: "3.1×", l: "Lead qualification speed" }, { v: "€1.8M", l: "Recovered pipeline visibility" }] },
        { tag: "Insurance · Agentforce + Data Cloud", t: "Customer-service AI agent on legacy stack", m: [{ v: "68%", l: "Tickets auto-resolved" }, { v: "11s", l: "Avg. first response" }, { v: "4 wks", l: "From kickoff to live" }] },
        { tag: "E-commerce · n8n + Make", t: "Order ops automated end-to-end", m: [{ v: "0", l: "Manual handoffs" }, { v: "−87%", l: "Order errors" }, { v: "12k+", l: "Workflows / month" }] },
      ],
    },
    industries: {
      eyebrow: "Industries we serve",
      list: ["Financial services", "Manufacturing", "Insurance", "Retail & e-commerce", "Logistics", "Professional services", "Healthcare", "Media & publishing"],
    },
    testimonials: {
      eyebrow: "What partners say",
      items: [
        { q: "Velior didn't sell us Salesforce — they sold us an outcome, then delivered it three weeks early.", n: "Marco Bellini", r: "COO, mid-market manufacturer" },
        { q: "The team's depth across Salesforce, n8n and custom Python is rare. We replaced two vendors with one.", n: "Anna Rossi", r: "Head of Digital, retail group" },
        { q: "Quietly excellent. Code is clean, communication is precise, no theatre.", n: "Luca Conti", r: "CTO, SaaS scale-up" },
      ],
    },
    contact: {
      eyebrow: "Let's talk",
      title: "Tell us about your next move.",
      lede: "We'll reply within one business day with a concrete next step. No sales theatre.",
      form: {
        firstName: "First name",
        lastName: "Last name",
        company: "Company",
        email: "Work email",
        topic: "What can we help with?",
        topics: ["Salesforce", "Custom software", "AI & data", "Process automation"],
        message: "A few sentences on the project",
        submit: "Send message",
        sent: "Message received. We'll be in touch within one business day.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, AL · Tallinn, EE",
        hours: "Mon–Fri, 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "About Velior",
      title: "A European consultancy for ambitious operators.",
      lede: "Founded by engineers tired of CRM theatre, Velior delivers Salesforce, automation, and custom software with the rigor of a product team and the discretion of a private partner.",
      values: [
        { t: "Outcome over output", d: "We bill by milestone, not seat. If it doesn't move a metric you care about, we don't ship it." },
        { t: "Rigor without bureaucracy", d: "Senior engineers on every call. No layered account management between you and the people writing the code." },
        { t: "Built to be inherited", d: "Documentation, tests and runbooks come standard. We expect you'll outgrow needing us." },
      ],
      stats: [
        { v: "2025", l: "Founded" },
        { v: "17", l: "Engineers & consultants" },
        { v: "11", l: "Countries served" },
        { v: "98%", l: "Client retention" },
      ],
    },
    footer: {
      tagline: "CRM, automation, and AI engineered for growth.",
      sections: [
        { t: "Company", l: [["About", "about"], ["Services", "services"], ["Contact", "contact"]] as [string, string][] },
        { t: "Capabilities", l: [["Salesforce", "services"], ["Automation", "services"], ["Full-stack", "services"], ["AI & agents", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group · P.IVA IT00000000000",
      privacy: "Privacy",
      cookies: "Cookies",
    },
    ui: {
      learnMore: "Learn more",
      caseN: "case",
      whereWeOperate: "Where we operate.",
      quietlyExcellent: "Quietly excellent.",
      buildNext: ["Let's build your", "next chapter."] as [string, string],
      operatingPrinciples: "operating principles",
      whatWeBelieve: "What we believe, in practice.",
      threePillars: ["Three pillars.", "One operating system", "for your business."] as [string, string, string],
      pillar: "pillar",
      ambitiousOperators: ["A European consultancy for", "ambitious operators."] as [string, string],
      tellUs: ["Tell us about your", "next move."] as [string, string],
      messageReceived: "Message received.",
      techStack: "technology stack",
      activeCerts: "active certifications",
      implementations: "implementations",
      partnerSince: "partner since",
      contact: "Contact",
      email: "email",
      office: "office",
      hours: "hours",
    },
  },
  it: {
    nav: {
      home: "Home",
      about: "Chi siamo",
      services: "Servizi",
      contact: "Contatti",
      cta: "Prenota una consulenza",
    },
    hero: {
      eyebrow: "Salesforce Consulting Partner · Albania ed Estonia",
      title: ["CRM, automazione e AI", "al servizio della crescita."] as [string, string],
      lede: "Aiutiamo le aziende ambiziose a trasformare l'ecosistema Salesforce, l'automazione iPaaS e lo sviluppo full-stack in ricavi misurabili.",
      ctaPrimary: "Richiedi una consulenza gratuita",
      ctaSecondary: "Scopri i nostri servizi",
      stats: [
        { v: "30+", l: "Implementazioni Salesforce" },
        { v: "130+", l: "Certificazioni Salesforce" },
        { v: "40%", l: "Tempo operativo recuperato" },
        { v: "2", l: "Sedi · Tirana e Tallinn" },
      ],
    },
    partner: {
      eyebrow: "Salesforce Partner",
      title: "Certificati su tutta la piattaforma.",
      lede: "Da Sales Cloud ad Agentforce e Data Cloud — i nostri consulenti detengono certificazioni attive e rilasciano lavoro in produzione ogni trimestre. Velior è Salesforce Consulting Partner registrato.",
      certs: [
        "Salesforce Administrator",
        "Platform Developer I & II",
        "Sales Cloud Consultant",
        "Service Cloud Consultant",
        "Marketing Cloud Consultant",
        "Data Cloud Consultant",
        "Agentforce Specialist",
        "Tableau Certified Analyst",
        "MuleSoft Developer",
      ],
    },
    services: {
      eyebrow: "Cosa facciamo",
      title: "Quattro pilastri. Un sistema operativo per la tua azienda.",
      items: [
        {
          n: "01",
          t: "Ecosistema Salesforce",
          d: "Sales Cloud, Service Cloud, Marketing Cloud, Data Cloud, Tableau e Agentforce — implementati, integrati e ottimizzati per il ROI.",
          bullets: ["Implementazione & migrazione", "Sviluppo Lightning & Apex", "Reportistica & dashboard", "Agentforce & AI agents"],
        },
        {
          n: "02",
          t: "Sviluppo full-stack",
          d: "Software custom in Next.js, Node, Python e Go — costruito con lo stesso rigore delle piattaforme che integriamo.",
          bullets: ["App Next.js / Angular / Vue", "Servizi FastAPI & Node", "Postgres, Mongo, Redis", "DevOps & observability"],
        },
        {
          n: "03",
          t: "AI & agenti",
          d: "Sistemi LLM, RAG e agenti progettati per la produzione — radicati nei tuoi dati, governati e misurabili.",
          bullets: ["Pipeline LLM & RAG", "Embeddings & vector search", "Agentforce & agenti custom", "Valutazione & guardrail"],
        },
        {
          n: "04",
          t: "Process automation",
          d: "Workflow iPaaS end-to-end su n8n e Make. Eliminiamo il lavoro manuale, gli errori da copia-incolla e colleghiamo tutti i sistemi che già usi.",
          bullets: ["Workflow n8n & Make", "Orchestrazione API & webhook", "Pipeline di dati e documenti", "Monitoraggio operativo"],
        },
      ],
    },
    process: {
      eyebrow: "Come lavoriamo",
      title: "Dalla scoperta alla produzione, in passi chiari.",
      steps: [
        { n: "01", t: "Discovery", d: "Analizziamo stack, dati e processi per identificare colli di bottiglia e opportunità. Consegniamo una diagnosi scritta e una roadmap con priorità." },
        { n: "02", t: "Design", d: "Definiamo architettura della soluzione, modello dati, integrazioni e criteri di accettazione. Nulla viene costruito prima dell'approvazione di scope e risultati attesi." },
        { n: "03", t: "Implementazione", d: "Rilascio iterativo con demo periodiche e progresso trasparente. Codice pulito, revisionato e documentato in corsa — nessuna black box." },
        { n: "04", t: "Supporto", d: "Passaggio con training, runbook e SLA dedicato. Restiamo vicini per far evolvere la piattaforma con la crescita del business." },
      ],
    },
    cases: {
      eyebrow: "Lavori selezionati",
      title: "Risultati, non screenshot.",
      lede: "Alcuni progetti recenti. Nomi reali disponibili sotto NDA — contattaci per il deck completo.",
      items: [
        { tag: "Manifatturiero · Sales Cloud", t: "Pipeline unificata su 11 paesi UE", m: [{ v: "−42%", l: "Tempo di reporting" }, { v: "3.1×", l: "Velocità qualifica lead" }, { v: "€1.8M", l: "Pipeline recuperata" }] },
        { tag: "Assicurazioni · Agentforce + Data Cloud", t: "Agente AI di customer service su stack legacy", m: [{ v: "68%", l: "Ticket auto-risolti" }, { v: "11s", l: "Prima risposta media" }, { v: "4 sett.", l: "Dal via al live" }] },
        { tag: "E-commerce · n8n + Make", t: "Order ops automatizzate end-to-end", m: [{ v: "0", l: "Handoff manuali" }, { v: "−87%", l: "Errori d'ordine" }, { v: "12k+", l: "Workflow / mese" }] },
      ],
    },
    industries: {
      eyebrow: "Settori serviti",
      list: ["Servizi finanziari", "Manifatturiero", "Assicurazioni", "Retail & e-commerce", "Logistica", "Servizi professionali", "Sanità", "Media & editoria"],
    },
    testimonials: {
      eyebrow: "Cosa dicono i partner",
      items: [
        { q: "Velior non ci ha venduto Salesforce — ci ha venduto un risultato, poi l'ha consegnato tre settimane in anticipo.", n: "Marco Bellini", r: "COO, manifatturiero mid-market" },
        { q: "La profondità del team su Salesforce, n8n e Python custom è rara. Abbiamo sostituito due fornitori con uno.", n: "Anna Rossi", r: "Head of Digital, gruppo retail" },
        { q: "Eccellenza silenziosa. Codice pulito, comunicazione precisa, niente teatro.", n: "Luca Conti", r: "CTO, SaaS scale-up" },
      ],
    },
    contact: {
      eyebrow: "Parliamone",
      title: "Raccontaci la tua prossima mossa.",
      lede: "Rispondiamo entro un giorno lavorativo con un passo concreto. Niente teatro commerciale.",
      form: {
        firstName: "Nome",
        lastName: "Cognome",
        company: "Azienda",
        email: "Email aziendale",
        topic: "Su cosa possiamo aiutarti?",
        topics: ["Salesforce", "Software custom", "AI & dati", "Process automation"],
        message: "Qualche frase sul progetto",
        submit: "Invia messaggio",
        sent: "Messaggio ricevuto. Ti scriviamo entro un giorno lavorativo.",
      },
      detail: {
        email: "info@veliorgroup.com",
        location: "Tirana, AL · Tallinn, EE",
        hours: "Lun–Ven, 09:00–18:00 CET",
      },
    },
    about: {
      eyebrow: "Chi è Velior",
      title: "Una consulenza europea per operatori ambiziosi.",
      lede: "Fondata da ingegneri stanchi del teatro CRM, Velior consegna Salesforce, automazione e software custom con il rigore di un team di prodotto e la discrezione di un partner privato.",
      values: [
        { t: "Risultato sopra l'output", d: "Fatturiamo a milestone, non a seat. Se non muove una metrica che ti interessa, non lo rilasciamo." },
        { t: "Rigore senza burocrazia", d: "Ingegneri senior in ogni call. Niente account management che si frappone tra te e chi scrive il codice." },
        { t: "Costruito per essere ereditato", d: "Documentazione, test e runbook sono inclusi. Ci aspettiamo che presto non avrai più bisogno di noi." },
      ],
      stats: [
        { v: "2025", l: "Fondata" },
        { v: "17", l: "Ingegneri & consulenti" },
        { v: "11", l: "Paesi serviti" },
        { v: "98%", l: "Retention clienti" },
      ],
    },
    footer: {
      tagline: "CRM, automazione e AI al servizio della crescita.",
      sections: [
        { t: "Azienda", l: [["Chi siamo", "about"], ["Servizi", "services"], ["Contatti", "contact"]] as [string, string][] },
        { t: "Capabilities", l: [["Salesforce", "services"], ["Automazione", "services"], ["Full-stack", "services"], ["AI & agenti", "services"]] as [string, string][] },
      ],
      legal: "© 2026 Velior Group · P.IVA IT00000000000",
      privacy: "Privacy",
      cookies: "Cookie",
    },
    ui: {
      learnMore: "Scopri di più",
      caseN: "case",
      whereWeOperate: "Dove operiamo.",
      quietlyExcellent: "Eccellenza silenziosa.",
      buildNext: ["Costruiamo il tuo", "prossimo capitolo."] as [string, string],
      operatingPrinciples: "principi operativi",
      whatWeBelieve: "Cosa crediamo, nella pratica.",
      threePillars: ["Tre pilastri.", "Un sistema operativo", "per la tua azienda."] as [string, string, string],
      pillar: "pilastro",
      ambitiousOperators: ["Una consulenza europea per", "operatori ambiziosi."] as [string, string],
      tellUs: ["Raccontaci la tua", "prossima mossa."] as [string, string],
      messageReceived: "Messaggio ricevuto.",
      techStack: "stack tecnologico",
      activeCerts: "certificazioni attive",
      implementations: "implementazioni",
      partnerSince: "partner dal",
      contact: "Contatti",
      email: "email",
      office: "sede",
      hours: "orari",
    },
  },
} as const;
